service: wombat

frameworkVersion: ">=1.2.0 <2.0.0"

plugins:
  - serverless-single-page-app-plugin

custom:
  s3Bucket: ${file(./serverless.env.yml):dev.BUCKET}
  origin: ${file(./serverless.env.yml):dev.ORIGIN}

provider:
  name: aws
  runtime: nodejs6.10
  region: ${file(./serverless.env.yml):dev.REGION}

functions:
  currentTime:
    handler: lambda/ping/handler.endpoint
    events:
      - http:
          path: ping
          method: get

resources:
  Resources:
    WebAppS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.s3Bucket}
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: error.html
    WebAppS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: WebAppS3Bucket
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Action:
              - s3:GetObject
              Resource: arn:aws:s3:::${self:custom.s3Bucket}/*
              Principal: 
                AWS: "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${self:custom.origin}"
